---
streamlit:
  title: "Applied AI team's bot"
  tab_title: "LLM bot"
  assistant_intro_message: "สวัสดีค่ะ อาการวันนี้ของคุณเป็นอย่างไรบ้าง" 
  about: "this is a demo bot, author: Applied AI team"
